name: PHP CS Fixer

on: [push, pull_request]

jobs:
    serendipity_hq:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: ['7.4']
        name: PHP ${{ matrix.php }} on ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v1
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none # disable xdebug, pcov
                  tools: prestissimo, phive
                  extensions: intl

            - name: Install Composer deps
              run: |
                  composer update --no-interaction --no-suggest

            - name: Install Phive deps
                # PHPCSFixer: E82B2FB314E9906E
                # PHPStan: CF1A108D0E7AE720
                # PHPUnit: 4AA394086372C20A
              run: |
                  phive --no-progress install --trust-gpg-keys E82B2FB314E9906E,CF1A108D0E7AE720,4AA394086372C20A

            - name: Run PHP CS Fixer
              run: |
                  ./tools/php-cs-fixer fix --allow-risky yes --dry-run -v
